name: Hello Workflow

on:
  push:
    branches:
      - main  # or 'master' if that’s your main branch

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Say Hello
      run: echo "Hello from GitHub Actions!"
